name: Cypress Tests

on:
  push:
    branches:
      - main  # Run tests on push to main branch

jobs:
  cypress-run:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Clones your repository

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify Node.js version

      - name: Install Dependencies
        run: npm install  # Install project dependencies

      - name: Run Cypress Tests
        run: npx cypress run --spec cypress/e2e/web_tests/add_and_delete_handling.js  # Execute Cypress tests

      - name: Upload Test Reports
        if: always()  # Upload reports even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: cypress/reports  # Path where reports are stored
